{% set version = "5.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
{% set github = "https://github.com/tpq/propr" %}

package:
  name: r-propr
  version: {{ version|replace("-", "_") }}

source:
  url: "{{ github }}/archive/refs/tags/{{ version }}.tar.gz"
  sha256: c0a0cf8b007501919bbe0585e412a62902f61c70cc3dfa2b56546428b16db887

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    # - bioconductor-aldex2
    - r-corpcor
    - r-fastcluster
    - r-knitr
    # - bioconductor-limma
    - r-ppcor
    - r-rmarkdown
    - r-testthat
    - r-vegan
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    # - bioconductor-aldex2
    - r-corpcor
    - r-fastcluster
    - r-knitr
    # - bioconductor-limma
    - r-ppcor
    - r-rmarkdown
    - r-testthat
    - r-vegan

test:
  commands:
    - $R -e "library('propr')"           # [not win]
    - "\"%R%\" -e \"library('propr')\""  # [win]

about:
  home: http://github.com/tpq/propr
  license: GPL-2.0-only
  summary: An R package to calculate proportionality between vectors of compositional data
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - jacodela
    - suzannejin

# Package: propr
# Title: Calculating Proportionality Between Vectors of Compositional Data
# Version: 5.0.1
# URL: http://github.com/tpq/propr
# BugReports: http://github.com/tpq/propr/issues
# Authors@R: c(person("Thomas", "Quinn", email = "contacttomquinn@gmail.com", role = c("aut", "cre")), person("Suzanne", "Jin", email = "suzanne.jin.yao@gmail.com", role = "aut"), person("Ionas", "Erb", email = "ionas.erb@crg.eu", role = "aut"), person("David", "Lovell", email = "david.lovell@qut.edu.au", role = "aut"), person("Anders", "Bilgrau", email = "anders.ellern.bilgrau@gmail.com", role = "ctb"), person("Greg", "Gloor", email = "ggloor@uwo.ca", role = "ctb"), person("Ryan", "Moore", email = "rmm1047@gmail.com", role = "ctb"))
# Description: The bioinformatic evaluation of gene co-expression often begins with correlation-based analyses. However, correlation lacks validity when applied to relative data, including count data generated by next-generation sequencing. This package implements several metrics for proportionality, including phi [Lovell et al (2015) <DOI:10.1371/journal.pcbi.1004075>] and rho [Erb and Notredame (2016) <DOI:10.1007/s12064-015-0220-8>]. This package also implements several metrics for differential proportionality. Unlike correlation, these measures give the same result for both relative and absolute data.
# License: GPL-2
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 7.2.0
# Encoding: UTF-8
# Depends: methods, R (>= 3.2.2)
# Imports: Rcpp, stats
# Suggests: ALDEx2, corpcor, fastcluster, knitr, limma, parallel, ppcor, rmarkdown, testthat (>= 3.0.0), vegan
# LinkingTo: Rcpp
# NeedsCompilation: yes
